- name: restart services
  become: true
  become_method: su
  become_user: root
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: "{{ project_name }}"