- name: enable firewalld port
  ansible.posix.firewalld:
    port: "{{ project_port }}"
    permanent: yes
    state: enabled
    zone: public
- name: reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
