---
- name: find max gid or uid
  ansible.builtin.shell: "getent passwd| awk -F: '{print $3,$4}'|sort -n|tail -2|head -n 1|awk 'BEGIN{n=1;max=0;nu=0} {for(n=1;n<=NF;n++) {a[$n]=$n;if(a[$n]>=max)max=a[$n]} {print max} {max=0}}'"
  register: max_gid